version: '3.7'

services:
  client:
    container_name: make-a-note-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      # exposed:container
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true