version: '3.7'

services:
  server:
    container_name: make-a-note-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/server'
      - '/server/node_modules'
    ports:
      # exposed:container
      - 3002:3002
    environment:
      - CHOKIDAR_USEPOLLING=true